spring.application.name=FluxbankAPI
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/fluxbank}
server.port=8081

# Database credentials
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Variables
jwt.secret=${JWT_SECRET:}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs