CREATE TABLE tb_accounts (
id UUID PRIMARY KEY,
holder_name VARCHAR(255) NOT NULL,
cpf VARCHAR(14) UNIQUE NOT NULL,
email VARCHAR(255) UNIQUE NOT NULL,
balance NUMERIC(19,2) NOT NULL,
account_type VARCHAR(50) NOT NULL,
created_at TIMESTAMP NOT NULL
);